//! Test d'integrazione del parser dei file di checksum.

use hasher::backend::algo::Algo;
use hasher::backend::checksum_file::{is_checksum_file, load, parse_text, ChecksumEntry};
use std::path::Path;

const MD5_EMPTY: &str = "d41d8cd98f00b204e9800998ecf8427e";
const MD5_ABC: &str = "900150983cd24fb0d6963f7d28e17f72";
const SHA256_ABC: &str = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad";

fn entry(algo: Option<Algo>, hex: &str, name: &str, line: usize) -> ChecksumEntry {
    ChecksumEntry {
        algo,
        hex: hex.to_string(),
        file_name: name.to_string(),
        line,
    }
}

#[test]
fn gnu_format() {
    let text = format!(
        "{MD5_EMPTY}  empty.txt\n\
         {} *abc.bin\n\
         {MD5_ABC} single space.txt\n\
         {MD5_ABC}  dir/sub dir/file name.txt\n",
        MD5_ABC.to_uppercase()
    );
    let entries = parse_text(&text, Some(Algo::Md5));
    assert_eq!(
        entries,
        vec![
            entry(Some(Algo::Md5), MD5_EMPTY, "empty.txt", 1),
            entry(Some(Algo::Md5), MD5_ABC, "abc.bin", 2),
            entry(Some(Algo::Md5), MD5_ABC, "single space.txt", 3),
            entry(Some(Algo::Md5), MD5_ABC, "dir/sub dir/file name.txt", 4),
        ]
    );
}

#[test]
fn gnu_without_default_algo_uses_length() {
    let text = format!("{SHA256_ABC}  a\n{MD5_ABC}  b\n");
    let entries = parse_text(&text, None);
    assert_eq!(entries[0].algo, None);
    assert!(entries[0].candidate_algos().contains(&Algo::Sha256));
    assert_eq!(entries[1].candidate_algos(), Algo::candidates_for_hex_len(32));
}

#[test]
fn default_algo_only_when_length_matches() {
    // Una riga SHA-256 dentro un file `.md5`: niente MD5 forzato.
    let text = format!("{SHA256_ABC}  a\n{MD5_ABC}  b\n");
    let entries = parse_text(&text, Some(Algo::Md5));
    assert_eq!(entries[0].algo, None);
    assert_eq!(entries[1].algo, Some(Algo::Md5));
}

#[test]
fn bsd_format() {
    let text = format!(
        "SHA256 (abc.txt) = {SHA256_ABC}\n\
         SHA-256 (with (parens).txt) = {}\n\
         MD5 (empty) = {MD5_EMPTY}\n\
         RIPEMD160 (r.bin) = 8eb208f7e05d987a9b044a8e98c6b087f15a0bfc\n\
         SHA256 (wrong-length) = {MD5_ABC}\n\
         WHIRLPOOL (unknown) = {}\n",
        SHA256_ABC.to_uppercase(),
        "ab".repeat(64)
    );
    let entries = parse_text(&text, Some(Algo::Md5));
    assert_eq!(
        entries,
        vec![
            entry(Some(Algo::Sha256), SHA256_ABC, "abc.txt", 1),
            entry(Some(Algo::Sha256), SHA256_ABC, "with (parens).txt", 2),
            entry(Some(Algo::Md5), MD5_EMPTY, "empty", 3),
            entry(
                Some(Algo::Ripemd160),
                "8eb208f7e05d987a9b044a8e98c6b087f15a0bfc",
                "r.bin",
                4
            ),
        ]
    );
}

#[test]
fn sfv_format() {
    let text = "; Generated by some tool\n\
                ;\n\
                file one.bin 352441C2\n\
                deadbeef 0badf00d\n\
                plain.txt\t00000000\n";
    let entries = parse_text(text, Some(Algo::Crc32));
    assert_eq!(
        entries,
        vec![
            entry(Some(Algo::Crc32), "352441c2", "file one.bin", 3),
            entry(Some(Algo::Crc32), "0badf00d", "deadbeef", 4),
            entry(Some(Algo::Crc32), "00000000", "plain.txt", 5),
        ]
    );
}

#[test]
fn sfv_shape_recognised_without_default_algo() {
    let entries = parse_text("movie.mkv 352441c2\n", None);
    assert_eq!(entries, vec![entry(None, "352441c2", "movie.mkv", 1)]);
    assert_eq!(entries[0].candidate_algos(), vec![Algo::Crc32]);
}

#[test]
fn comments_blank_lines_crlf_bom_and_trailing_whitespace() {
    let text =
        format!("\u{feff}# comment\r\n\r\n   \r\n; another\r\n{MD5_ABC}  abc.txt  \r\n\t{MD5_EMPTY} *e.txt\t\r\n");
    let entries = parse_text(&text, Some(Algo::Md5));
    assert_eq!(
        entries,
        vec![
            entry(Some(Algo::Md5), MD5_ABC, "abc.txt", 5),
            entry(Some(Algo::Md5), MD5_EMPTY, "e.txt", 6)
        ]
    );
}

#[test]
fn bad_lines_are_skipped() {
    let text = format!(
        "not a checksum line\n\
         12345  odd-length.txt\n\
         {}  wrong-length.txt\n\
         zz{}  not-hex.txt\n\
         {MD5_ABC}\n\
         {MD5_ABC}  \n\
         SHA256 () = {SHA256_ABC}\n\
         {MD5_ABC}  good.txt\n",
        "a".repeat(30),
        &MD5_ABC[2..]
    );
    let entries = parse_text(&text, None);
    assert_eq!(entries, vec![entry(None, MD5_ABC, "good.txt", 8)]);
}

#[test]
fn load_from_disk() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("list.SHA256");
    std::fs::write(&path, format!("\u{feff}{SHA256_ABC} *abc.txt\r\n").as_bytes()).unwrap();
    assert!(is_checksum_file(&path));
    let file = load(&path).unwrap();
    assert_eq!(file.path, path);
    assert_eq!(file.base_dir, dir.path());
    assert_eq!(file.default_algo, Some(Algo::Sha256));
    assert_eq!(file.entries, vec![entry(Some(Algo::Sha256), SHA256_ABC, "abc.txt", 1)]);

    // Byte non UTF-8 nel nome: lettura "lossy", la riga resta valida.
    let sfv = dir.path().join("set.sfv");
    let mut bytes = b"caf\xe9.bin 352441c2\n".to_vec();
    bytes.extend_from_slice(b"ok.bin 00000000\n");
    std::fs::write(&sfv, bytes).unwrap();
    let file = load(&sfv).unwrap();
    assert_eq!(file.default_algo, Some(Algo::Crc32));
    assert_eq!(file.entries.len(), 2);
    assert_eq!(file.entries[0].file_name, "caf\u{fffd}.bin");
    assert_eq!(file.entries[1], entry(Some(Algo::Crc32), "00000000", "ok.bin", 2));

    // Estensione sconosciuta: nessun algoritmo predefinito.
    let txt = dir.path().join("hashes.txt");
    std::fs::write(&txt, format!("{MD5_ABC}  abc.txt\n")).unwrap();
    let file = load(&txt).unwrap();
    assert_eq!(file.default_algo, None);
    assert_eq!(file.entries[0].algo, None);

    assert!(load(Path::new("/definitely/not/here.md5")).is_err());
}
