//! Test d'integrazione dell'esportazione: ogni formato viene scritto su disco e riletto.

use chrono::{DateTime, Local, TimeZone};
use hasher::backend::algo::Algo;
use hasher::backend::engine::FileResult;
use hasher::backend::export::{self, ExportFormat, ExportLabels, ExportOptions};
use hasher::backend::fileinfo::{FileAttr, FileInfo};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::Duration;

const CRC32_ABC: &str = "352441c2";
const MD5_ABC: &str = "900150983cd24fb0d6963f7d28e17f72";
const SHA256_ABC: &str = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad";
const MD5_EMPTY: &str = "d41d8cd98f00b204e9800998ecf8427e";
const SHA256_EMPTY: &str = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

const NA: &str = "N/A";
const NAME_1: &str = "abc.txt";
const NAME_2: &str = "senza date \u{e9}\u{fc}.bin";

fn local(y: i32, mo: u32, d: u32, h: u32, mi: u32, s: u32) -> DateTime<Local> {
    Local.with_ymd_and_hms(y, mo, d, h, mi, s).unwrap()
}

fn digests(pairs: &[(Algo, &str)]) -> BTreeMap<Algo, Vec<u8>> {
    pairs.iter().map(|(a, h)| (*a, hex::decode(h).unwrap())).collect()
}

/// File 1: tutti i campi. File 2: nessuna data, nessun attributo, manca CRC32.
fn sample_results() -> Vec<FileResult> {
    let full = FileResult {
        id: 1,
        info: FileInfo {
            path: PathBuf::from("/data/docs/abc.txt"),
            name: NAME_1.to_string(),
            extension: Some("txt".to_string()),
            size: 1_234_567,
            created: Some(local(2026, 1, 2, 12, 4, 5)),
            modified: Some(local(2026, 3, 4, 12, 5, 6)),
            accessed: Some(local(2026, 5, 6, 12, 6, 7)),
            attributes: vec![FileAttr::ReadOnly, FileAttr::Hidden],
            unix_mode: Some(0o644),
            is_symlink: false,
        },
        digests: digests(&[
            (Algo::Crc32, CRC32_ABC),
            (Algo::Md5, MD5_ABC),
            (Algo::Sha256, SHA256_ABC),
        ]),
        elapsed: Duration::from_millis(12),
    };
    let sparse = FileResult {
        id: 2,
        info: FileInfo {
            path: PathBuf::from("/data/docs/sub/senza date \u{e9}\u{fc}.bin"),
            name: NAME_2.to_string(),
            extension: Some("bin".to_string()),
            size: 0,
            created: None,
            modified: None,
            accessed: None,
            attributes: vec![],
            unix_mode: None,
            is_symlink: false,
        },
        digests: digests(&[(Algo::Md5, MD5_EMPTY), (Algo::Sha256, SHA256_EMPTY)]),
        elapsed: Duration::ZERO,
    };
    vec![full, sparse]
}

fn labels() -> ExportLabels {
    ExportLabels {
        title: "Hash report".into(),
        generated_by: "Generated by".into(),
        generated_at: "Generated on".into(),
        file: "File".into(),
        path: "Path".into(),
        size: "Size".into(),
        size_bytes: "Size (bytes)".into(),
        created: "Created".into(),
        modified: "Modified".into(),
        attributes: "Attributes".into(),
        permissions: "Permissions".into(),
        algorithm: "Algorithm".into(),
        hash: "Hash".into(),
        files_count: "Files".into(),
        elapsed: "Elapsed".into(),
        not_available: NA.into(),
    }
}

fn options(uppercase: bool) -> ExportOptions {
    ExportOptions {
        algos: vec![Algo::Crc32, Algo::Md5, Algo::Sha256],
        uppercase_hex: uppercase,
        labels: labels(),
        app_name: "Hasher".into(),
        app_version: "1.2.3".into(),
        company: "Martini Multimedia s.a.s.".into(),
        generated_at: local(2026, 10, 9, 12, 30, 15),
        date_format: "%d/%m/%Y %H:%M:%S".into(),
    }
}

/// Esporta in una cartella temporanea e restituisce (cartella, percorso del file).
fn run(format: ExportFormat, results: &[FileResult], opts: &ExportOptions) -> (tempfile::TempDir, PathBuf) {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join(format!("out.{}", format.extension()));
    export::export(&path, format, results, opts).unwrap_or_else(|e| panic!("{format:?}: {e:#}"));
    assert!(path.is_file(), "{format:?}: file not created");
    assert!(std::fs::metadata(&path).unwrap().len() > 0, "{format:?}: empty file");
    (dir, path)
}

fn read_text(path: &Path) -> String {
    String::from_utf8(std::fs::read(path).unwrap()).expect("output must be UTF-8")
}

fn contains_bytes(haystack: &[u8], needle: &[u8]) -> bool {
    haystack.windows(needle.len()).any(|w| w == needle)
}

// ---------------------------------------------------------------------------------- TXT

#[test]
fn txt_report_content() {
    let (_d, path) = run(ExportFormat::Txt, &sample_results(), &options(false));
    let txt = read_text(&path);
    assert!(!txt.contains('\r'), "TXT must use \\n line endings");
    assert!(txt.starts_with("Hash report\n===========\n"), "{txt}");
    assert!(txt.contains("Generated by: Hasher 1.2.3 \u{2014} Martini Multimedia s.a.s.\n"));
    assert!(txt.contains("Generated on: 09/10/2026 12:30:15\n"));
    assert!(txt.contains("Files: 2\n"));
    assert!(txt.contains(NAME_1));
    assert!(txt.contains(NAME_2));
    assert!(txt.contains("/data/docs/abc.txt"));
    assert!(txt.contains("1.23 MB"));
    assert!(txt.contains("1234567"));
    assert!(txt.contains("02/01/2026 12:04:05"));
    assert!(txt.contains("RH"));
    assert!(txt.contains("rw-r--r--"));
    // Algoritmi allineati al nome più lungo (SHA-256) e hash esatti.
    assert!(txt.contains(&format!("SHA-256: {SHA256_ABC}\n")), "{txt}");
    assert!(txt.contains(&format!("MD5    : {MD5_ABC}\n")));
    assert!(txt.contains(&format!("CRC32  : {CRC32_ABC}\n")));
    // Il secondo file non ha CRC32.
    assert!(txt.contains("CRC32  : N/A\n"));
    // Attributi e permessi: solo per il primo file.
    assert_eq!(txt.matches("Attributes").count(), 1);
    assert_eq!(txt.matches("Permissions").count(), 1);
    // Date assenti.
    assert!(txt.contains("Created     : N/A"));
    // Piè di pagina.
    assert!(txt
        .trim_end()
        .ends_with("Hasher 1.2.3 \u{2014} Martini Multimedia s.a.s."));
}

// ---------------------------------------------------------------------------------- CSV

#[test]
fn csv_has_bom_and_parses_back() {
    let (_d, path) = run(ExportFormat::Csv, &sample_results(), &options(false));
    let bytes = std::fs::read(&path).unwrap();
    assert!(bytes.starts_with(b"\xEF\xBB\xBF"), "missing UTF-8 BOM");

    let mut rdr = csv::ReaderBuilder::new().delimiter(b',').from_reader(&bytes[3..]);
    let header: Vec<String> = rdr.headers().unwrap().iter().map(String::from).collect();
    assert_eq!(header.len(), 8 + 3);
    assert_eq!(
        header,
        [
            "File",
            "Path",
            "Size (bytes)",
            "Size",
            "Created",
            "Modified",
            "Attributes",
            "Permissions",
            "CRC32",
            "MD5",
            "SHA-256"
        ]
    );

    let rows: Vec<csv::StringRecord> = rdr.records().map(|r| r.unwrap()).collect();
    assert_eq!(rows.len(), 2);
    assert!(rows.iter().all(|r| r.len() == header.len()));

    let r0 = &rows[0];
    assert_eq!(&r0[0], NAME_1);
    assert_eq!(&r0[1], "/data/docs/abc.txt");
    assert_eq!(&r0[2], "1234567");
    assert_eq!(&r0[3], "1.23 MB");
    assert_eq!(&r0[4], "02/01/2026 12:04:05");
    assert_eq!(&r0[5], "04/03/2026 12:05:06");
    assert_eq!(&r0[6], "RH");
    assert_eq!(&r0[7], "rw-r--r--");
    assert_eq!(&r0[8], CRC32_ABC);
    assert_eq!(&r0[9], MD5_ABC);
    assert_eq!(&r0[10], SHA256_ABC);

    let r1 = &rows[1];
    assert_eq!(&r1[0], NAME_2);
    assert_eq!(&r1[2], "0");
    assert_eq!(&r1[4], NA);
    assert_eq!(&r1[6], "");
    assert_eq!(&r1[7], "");
    assert_eq!(&r1[8], NA, "missing algorithm must be not_available");
    assert_eq!(&r1[10], SHA256_EMPTY);
}

#[test]
fn csv_quotes_special_characters_and_defuses_formulas() {
    let mut results = sample_results();
    results[0].info.name = "a,\"b\".txt".to_string();
    results[1].info.name = "=HYPERLINK(\"http://x\")".to_string();
    let (_d, path) = run(ExportFormat::Csv, &results, &options(false));
    let bytes = std::fs::read(&path).unwrap();
    let mut rdr = csv::Reader::from_reader(&bytes[3..]);
    let rows: Vec<csv::StringRecord> = rdr.records().map(|r| r.unwrap()).collect();
    assert_eq!(&rows[0][0], "a,\"b\".txt");
    assert_eq!(&rows[1][0], "'=HYPERLINK(\"http://x\")");
}

// --------------------------------------------------------------------------------- JSON

#[test]
fn json_parses_back() {
    let (_d, path) = run(ExportFormat::Json, &sample_results(), &options(false));
    let text = read_text(&path);
    let v: serde_json::Value = serde_json::from_str(&text).unwrap();

    assert_eq!(v["app"]["name"], "Hasher");
    assert_eq!(v["app"]["version"], "1.2.3");
    assert_eq!(v["app"]["company"], "Martini Multimedia s.a.s.");
    let generated = DateTime::parse_from_rfc3339(v["generated_at"].as_str().unwrap()).unwrap();
    assert_eq!(generated.timestamp(), local(2026, 10, 9, 12, 30, 15).timestamp());

    let files = v["files"].as_array().unwrap();
    assert_eq!(files.len(), 2);

    let f0 = &files[0];
    assert_eq!(f0["name"], NAME_1);
    assert_eq!(f0["path"], "/data/docs/abc.txt");
    assert_eq!(f0["size"], 1_234_567);
    assert_eq!(f0["size_human"], "1.23 MB");
    assert_eq!(f0["hashes"]["sha256"], SHA256_ABC);
    assert_eq!(f0["hashes"]["md5"], MD5_ABC);
    assert_eq!(f0["hashes"]["crc32"], CRC32_ABC);
    assert_eq!(f0["attributes"], serde_json::json!(["read_only", "hidden"]));
    assert_eq!(f0["permissions"], "rw-r--r--");
    for key in ["created", "modified", "accessed"] {
        let s = f0[key].as_str().unwrap_or_else(|| panic!("{key} must be a string"));
        DateTime::parse_from_rfc3339(s).unwrap_or_else(|e| panic!("{key}: {e}"));
    }
    assert_eq!(
        DateTime::parse_from_rfc3339(f0["created"].as_str().unwrap())
            .unwrap()
            .timestamp(),
        local(2026, 1, 2, 12, 4, 5).timestamp()
    );

    let f1 = &files[1];
    assert_eq!(f1["name"], NAME_2);
    assert_eq!(f1["size"], 0);
    assert!(f1["created"].is_null());
    assert!(f1["modified"].is_null());
    assert!(f1["accessed"].is_null());
    assert!(f1["permissions"].is_null());
    assert_eq!(f1["attributes"], serde_json::json!([]));
    assert!(f1["hashes"]["crc32"].is_null(), "missing algorithm must be null");
    assert_eq!(f1["hashes"]["sha256"], SHA256_EMPTY);

    // L'ordine delle chiavi segue `opts.algos`.
    let (a, b, c) = (
        text.find("\"crc32\"").unwrap(),
        text.find("\"md5\"").unwrap(),
        text.find("\"sha256\"").unwrap(),
    );
    assert!(a < b && b < c, "hash keys out of order");
    assert!(text.contains("\n  \"app\""), "output must be pretty printed");
}

// --------------------------------------------------------------------------------- XLSX

#[test]
fn xlsx_is_a_zip_with_two_sheets() {
    let (_d, path) = run(ExportFormat::Xlsx, &sample_results(), &options(false));
    let bytes = std::fs::read(&path).unwrap();
    assert!(bytes.starts_with(b"PK\x03\x04"), "not a ZIP container");
    assert!(bytes.len() > 1000, "suspiciously small: {} bytes", bytes.len());
    assert!(contains_bytes(&bytes, b"xl/worksheets/sheet1.xml"));
    assert!(contains_bytes(&bytes, b"xl/worksheets/sheet2.xml"));
    assert!(contains_bytes(&bytes, b"xl/workbook.xml"));
}

#[test]
fn xlsx_handles_empty_input_and_wide_hashes() {
    let mut opts = options(false);
    opts.algos = Algo::ALL.to_vec();
    run(ExportFormat::Xlsx, &[], &opts);
    run(ExportFormat::Xlsx, &sample_results(), &opts);
    opts.algos.clear();
    run(ExportFormat::Xlsx, &sample_results(), &opts);
}

// --------------------------------------------------------------------------------- DOCX

#[test]
fn docx_is_a_zip_with_document_part() {
    let (_d, path) = run(ExportFormat::Docx, &sample_results(), &options(false));
    let bytes = std::fs::read(&path).unwrap();
    assert!(bytes.starts_with(b"PK\x03\x04"), "not a ZIP container");
    assert!(bytes.len() > 1000, "suspiciously small: {} bytes", bytes.len());
    assert!(contains_bytes(&bytes, b"word/document.xml"));
    assert!(contains_bytes(&bytes, b"[Content_Types].xml"));
}

#[test]
fn docx_handles_empty_input_and_wide_hashes() {
    let mut opts = options(false);
    opts.algos = Algo::ALL.to_vec();
    run(ExportFormat::Docx, &[], &opts);
    run(ExportFormat::Docx, &sample_results(), &opts);
    opts.algos.clear();
    run(ExportFormat::Docx, &sample_results(), &opts);
}

// ---------------------------------------------------------------------------- checksum

/// Righe non di commento e non vuote.
fn data_lines(text: &str, comment: char) -> Vec<&str> {
    text.lines()
        .filter(|l| !l.is_empty() && !l.starts_with(comment))
        .collect()
}

#[test]
fn checksum_gnu_format() {
    let (_d, path) = run(ExportFormat::Checksum(Algo::Sha256), &sample_results(), &options(false));
    assert_eq!(path.extension().unwrap(), "sha256");
    let text = read_text(&path);
    assert!(!text.contains('\r'));

    let mut lines = text.lines();
    assert_eq!(
        lines.next().unwrap(),
        "# Hasher 1.2.3 \u{2014} Martini Multimedia s.a.s."
    );
    assert_eq!(lines.next().unwrap(), "# Generated on: 09/10/2026 12:30:15");

    let entries: Vec<(&str, &str)> = data_lines(&text, '#')
        .into_iter()
        .map(|l| l.split_once("  ").expect("two spaces"))
        .collect();
    assert_eq!(entries, vec![(SHA256_ABC, NAME_1), (SHA256_EMPTY, NAME_2)]);
    assert!(!text.contains(NA), "no skipped files expected for SHA-256");
}

#[test]
fn checksum_skips_files_without_the_algorithm() {
    let (_d, path) = run(ExportFormat::Checksum(Algo::Md5), &sample_results(), &options(false));
    let text = read_text(&path);
    assert_eq!(data_lines(&text, '#').len(), 2);

    let mut results = sample_results();
    results[1].digests.remove(&Algo::Md5);
    let (_d, path) = run(ExportFormat::Checksum(Algo::Md5), &results, &options(false));
    let text = read_text(&path);
    assert_eq!(data_lines(&text, '#'), vec![format!("{MD5_ABC}  {NAME_1}")]);
    assert!(text.lines().last().unwrap().starts_with('#'));
    assert!(text.contains("# MD5 N/A: 1"), "{text}");
}

#[test]
fn checksum_sfv_format_for_crc32() {
    let mut opts = options(false); // anche con hex minuscolo: SFV è sempre maiuscolo
    opts.uppercase_hex = false;
    let (_d, path) = run(ExportFormat::Checksum(Algo::Crc32), &sample_results(), &opts);
    assert_eq!(path.extension().unwrap(), "sfv");
    let text = read_text(&path);

    let mut lines = text.lines();
    assert_eq!(
        lines.next().unwrap(),
        "; Hasher 1.2.3 \u{2014} Martini Multimedia s.a.s."
    );
    assert_eq!(lines.next().unwrap(), "; Generated on: 09/10/2026 12:30:15");
    assert!(!text.contains('#'));
    // Il secondo file non ha CRC32: saltato e contato in un commento.
    assert_eq!(
        data_lines(&text, ';'),
        vec![format!("{NAME_1} {}", CRC32_ABC.to_uppercase())]
    );
    assert!(text.lines().last().unwrap().starts_with(';'));
    assert!(text.contains("; CRC32 N/A: 1"), "{text}");
}

#[test]
fn checksum_files_roundtrip_through_the_parser() {
    use hasher::backend::checksum_file::parse_text;

    let mut results = sample_results();
    results[1].info.name = "we\\ird\nname.bin".to_string(); // backslash e ritorno a capo
    let opts = options(false);

    let text = read_text(&run(ExportFormat::Checksum(Algo::Sha256), &results, &opts).1);
    let entries = parse_text(&text, Some(Algo::Sha256));
    assert_eq!(entries.len(), 2, "{text}");
    assert_eq!(
        (entries[0].hex.as_str(), entries[0].file_name.as_str()),
        (SHA256_ABC, NAME_1)
    );
    assert_eq!(
        (entries[1].hex.as_str(), entries[1].file_name.as_str()),
        (SHA256_EMPTY, "we\\ird\nname.bin")
    );
    assert!(
        text.contains("\\\\ird\\nname.bin"),
        "name must be escaped GNU style: {text}"
    );

    let text = read_text(&run(ExportFormat::Checksum(Algo::Crc32), &results, &opts).1);
    let entries = parse_text(&text, Some(Algo::Crc32));
    assert_eq!(entries.len(), 1, "{text}");
    assert_eq!(
        (entries[0].hex.as_str(), entries[0].file_name.as_str()),
        (CRC32_ABC, NAME_1)
    );
}

// --------------------------------------------------------------------------- uppercase

#[test]
fn uppercase_hex_affects_every_format() {
    let results = sample_results();
    let lower = options(false);
    let upper = options(true);

    // TXT
    let txt_l = read_text(&run(ExportFormat::Txt, &results, &lower).1);
    let txt_u = read_text(&run(ExportFormat::Txt, &results, &upper).1);
    assert!(txt_l.contains(SHA256_ABC) && !txt_l.contains(&SHA256_ABC.to_uppercase()));
    assert!(txt_u.contains(&SHA256_ABC.to_uppercase()) && !txt_u.contains(SHA256_ABC));

    // CSV
    let csv_u = read_text(&run(ExportFormat::Csv, &results, &upper).1);
    assert!(csv_u.contains(&SHA256_ABC.to_uppercase()) && !csv_u.contains(SHA256_ABC));

    // JSON
    let json_u = read_text(&run(ExportFormat::Json, &results, &upper).1);
    let v: serde_json::Value = serde_json::from_str(&json_u).unwrap();
    assert_eq!(v["files"][0]["hashes"]["sha256"], SHA256_ABC.to_uppercase());

    // Checksum GNU
    let sum_u = read_text(&run(ExportFormat::Checksum(Algo::Sha256), &results, &upper).1);
    assert!(sum_u.contains(&format!("{}  {NAME_1}", SHA256_ABC.to_uppercase())));

    // SFV: maiuscolo in ogni caso.
    let sfv_l = read_text(&run(ExportFormat::Checksum(Algo::Crc32), &results, &lower).1);
    let sfv_u = read_text(&run(ExportFormat::Checksum(Algo::Crc32), &results, &upper).1);
    assert_eq!(data_lines(&sfv_l, ';'), data_lines(&sfv_u, ';'));
}

// ------------------------------------------------------------------------ dispatcher

#[test]
fn every_basic_format_and_empty_input() {
    let opts = options(false);
    for format in ExportFormat::BASIC {
        run(format, &sample_results(), &opts);
        run(format, &[], &opts);
    }
    for algo in [Algo::Crc32, Algo::Md5, Algo::Sha256] {
        run(ExportFormat::Checksum(algo), &[], &opts);
    }
}

#[test]
fn unwritable_destination_reports_the_path() {
    let dir = tempfile::tempdir().unwrap();
    let missing = dir.path().join("no-such-dir").join("out");
    let opts = options(false);
    for format in ExportFormat::BASIC
        .into_iter()
        .chain([ExportFormat::Checksum(Algo::Md5), ExportFormat::Checksum(Algo::Crc32)])
    {
        let err = export::export(&missing, format, &sample_results(), &opts).expect_err("must fail");
        let msg = format!("{err:#}");
        assert!(msg.contains("no-such-dir"), "{format:?}: error without path: {msg}");
    }
}
